### ISSUE TITLE
Line drawings ?

### ISSUE THREAD

**Issue by goswinr** [dlbeer/fspdf#1]
can I also draw lines and polylines in a PDF with this tools?

**Comment by dlbeer** [comment]
Yes, although you might prefer to do that with a higher-level tool (or write something to assist), depending on what you're doing. You can store arbitrary content streams, so anything that goes in a content stream can be done.

**Comment by goswinr** [comment]
Thanks, I would like to understand the low level part of it.  what is the best place to look up the content stream needed for a polyline, line or hatch (fill) ?

**Comment by dlbeer** [comment]
On Mon, Mar 20, 2017 at 10:58:48PM -0700, Goswin wrote:
> Thanks, what is the best place to look up the content stream needed
> for a polyline, line or hatch (fill) ?

Probably the best reference is the ISO 32000 document. Check out Section
8 ("Graphics"), and perhaps a little of Section 7 ("Syntax"), which
describes the PDF file structure.

The included example.fs shows how to embed a content stream in a
one-page document.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by goswinr** [comment]
Thanks, I was impressed by your code and how little is needed to get a low level tool done.
